### ISSUE TITLE
Add sanitilize log cli and pretty-printers

### ISSUE THREAD

**Issue by safl** [xnvme/xnvme#518]
To add support for sanitize-log then the following needs to be done:

# Tasks

- [x] Add data-structure to ``libxnvme_spec.h``
- [x] Add a pretty-printer for the log-page structure in ``lib/xnvme_spec.c``
- [x] Add a sub-command to the ``xnvme`` cli-tool that sends get-log-page for the sanitize command status in ``tools/xnvme.c`` using ``xnvme_prep_adm_log()`` and the pretty-printer added above

# For guidance

The **API** function (``xnvme_prep_adm_log()``) takes care of the command-construction, submission, and completion, examples of its use are available in the cli-tools ``xnvme``, below are a couple of examples:

- S.M.A.R.T. / Health Information (https://github.com/xnvme/xnvme/blob/5fbaf6a0960a567fdb377b2aeb82b8838d674f3b/tools/xnvme.c#L232)
- Error Information: https://github.com/xnvme/xnvme/blob/5fbaf6a0960a567fdb377b2aeb82b8838d674f3b/tools/xnvme.c#L273
- FDP Config (https://github.com/xnvme/xnvme/blob/5fbaf6a0960a567fdb377b2aeb82b8838d674f3b/tools/xnvme.c#L324)

Examples of "pretty-printers", these live together with the layout definitions from the spec, here is an example:

* Data-structure definition
https://github.com/xnvme/xnvme/blob/5fbaf6a0960a567fdb377b2aeb82b8838d674f3b/include/libxnvme_spec.h#L195
* Pretty-printers
  - https://github.com/xnvme/xnvme/blob/5fbaf6a0960a567fdb377b2aeb82b8838d674f3b/lib/xnvme_spec.c#L23
  - https://github.com/xnvme/xnvme/blob/5fbaf6a0960a567fdb377b2aeb82b8838d674f3b/lib/xnvme_spec.c#L81

**Comment by karlowich** [comment]
#561 has been merged, thus closing this.
